export const SHAPES = [
    { id: "line", name: "Линия", defaultSize: { width: 80, height: 0 } },
    { id: 'arrow', name: 'Стрелка', defaultSize: { width: 180, height: 60 } },
    { id: 'dblarrow', name: 'Двойная стрелка', defaultSize: { width: 200, height: 60 } },
    { id: 'square', name: 'Квадрат', defaultSize: { width: 140, height: 140 } },
    { id: 'circle', name: 'Круг', defaultSize: { width: 140, height: 140 } },
    { id: 'triangle', name: 'Треугольник', defaultSize: { width: 160, height: 150 } },
    { id: 'star', name: 'Звезда', defaultSize: { width: 160, height: 160 } },
    { id: 'parallelogram', name: 'Параллелограмм', defaultSize: { width: 200, height: 120 } },
    { id: 'stick', name: 'Палка', defaultSize: { width: 20, height: 160 } },
    { id: 'roundedRect', name: 'Скруглённый прямоугольник', defaultSize: { width: 160, height: 100 } },
    { id: 'capsule', name: 'Капсула', defaultSize: { width: 160, height: 60 } },
    { id: 'pentagon', name: 'Пятиугольник', defaultSize: { width: 140, height: 140 } },
    { id: 'cloud', name: 'Облако', defaultSize: { width: 180, height: 120 } },
    { id: 'speech', name: 'Облачко речи', defaultSize: { width: 180, height: 120 } },
    { id: 'chevron', name: 'Шеврон', defaultSize: { width: 160, height: 80 } },
    { id: 'table3x3', name: 'Таблица 3×3', defaultSize: { width: 180, height: 180 } },
    { id: 'pyramid', name: 'Пирамида', defaultSize: { width: 160, height: 160 } },
    { id: 'circleArrow', name: 'Круг со стрелкой', defaultSize: { width: 140, height: 140 } },
    { id: 'table3x3LeftMerge', name: 'Таблица 3×3', defaultSize: { width: 180, height: 180 } },
];
